### ISSUE TITLE
progress counting

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-engine-serial#11]
Trying out r-w-e-serial published version 0.3.0.dev20180418, I'm seeing what seems to be a off-by-one progress counting bug:

```console
$ reana-client workflow status
STATUS    COMMAND                                             PROGRESS 
running   root -b -q '../code/gendata.C(20000,"data.root")'   None/None
 $ reana-client workflow status
STATUS    COMMAND                                             PROGRESS 
 running   root -b -q '../code/gendata.C(20000,"data.root")'   None/None
$ reana-client workflow status
STATUS    COMMAND                                                  PROGRESS
running   root -b -q '../code/fitdata.C("data.root","plot.png")'   1/2     
$ reana-client workflow status
STATUS     COMMAND   PROGRESS
finished   exit      2/2     
```

If the current step is not counted in "progress", we should display gendata 0/2 instead of None/None.

If the current step is counted in the "progress", we should display gendata 1/2 fitdata 2/2.

I think the latter might be more user-friendly: the "progress" shows which step is currently running, and "status" whether it is still running or whether it was finished.  This would give the following progression:

```
created 0/2 
running 1/2 gendata 
running 2/2 fitdata
finished 2/2
```

@dinosk Can you please have a look?

**Comment by lukasheinrich** [comment]
is there an issue on how the progress is implemented / shown for other engines. I think at a minimum "x/n" steps could be done by all engines. Though, part of the dynamism of yadage and cwl etc is that the total number of steps is/maybe unknown upfront

**Comment by tiborsimko** [comment]
@lukasheinrich I think @dinosk started to look at the Yadage where to plug progress setting, see https://github.com/reanahub/reana-workflow-engine-yadage/issues/64. We have also talked about "linearised" step counting... Might be perhaps good if you stop by one of these days to help with this? 
(We can also revive logstash at the same time, but only after the 20 June workshop...)

**Comment by lukasheinrich** [comment]
Hi @dinosk @tiborsimko ,

yadage has hooks to add custom progress tracking classes. This is an example of a text-based user interface that shows a linearized progress.. as you can see the total number of steps increases as nodes are added to the workflow graph:

https://asciinema.org/a/hFqqdjj9VPwrY9M33tZu8QMF6

**Comment by tiborsimko** [comment]
(BTW WRT `logstash` musings, there is now `fluentd` deployed on the CERN Kubernetes infrastructure)
