### ISSUE TITLE
reana.yaml: maintaining outputs section

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-workflow-engine-serial#25]
After PR https://github.com/reanahub/reana-workflow-engine-serial/pull/23 the `outputs` section in reana.yaml might not be necessary for serial workflows. By maintaining it, it is possible to have a command to get all outputs for example, so it might serve a purpose in that way.

**Comment by tiborsimko** [comment]
Yes, the `inputs/outputs` sections in `reana.yaml` are is useful for wrapper commands, see https://github.com/reanahub/reana-client/issues/172 and https://github.com/reanahub/reana-client/issues/173

**Comment by diegodelemos** [comment]
Closing as it was decided to keep that section.
