### ISSUE TITLE
docs: richer user guide

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-engine-serial#40]
Introduce usual Getting started, User guide, Developer guide page structure.  See other modules. 

Describe in the user guide the caching feature. How to turn it off or on via `reana-client`. Warn users in case of environment docker images changes or in case the workflow contains random generators.     

Decide about the best default, caching on or off. Former is nice but may be aggressive. Latter is safer but less nice. 

Investigate whether CACHING=0/1 may be used instead of CACHING=true/false.

**Comment by tiborsimko** [comment]
... and can also include a separate v0.3.1 release commit afterwards.

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-workflow-engine-serial/pull/41 and https://github.com/reanahub/reana-client/pull/167.
