### ISSUE TITLE
global: serverless Serial workflow engine

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-workflow-engine-serial#5]
Currently the workflow engine pods persist in the cluster and run the celery worker which executes incoming jobs. By bringing up the engine pods for each job, we can move towards arbitrary environments for each job step, and later on implement caching.

For the above, changes need to made in job-controller and all engine pods to implement the logic the celery worker differently.

**Comment by diegodelemos** [comment]
We should offer a way of running workflow engines only one, so each user workflow is run in total isolation and then, REANA cluster will only have RWE_'s when it is necessary.

One could imagine that removing Celery and offering an interface that can be run as the Docker command, i.e. a CLI on top of each implementation to have a common interface and then link to each workflow runner internals:

```diff
...
- CMD celery -A reana_workflow_engine_cwl.celeryapp worker -l info -Q ${QUEUE_ENV} --concurrency ${CELERY_CONCURRENCY} -Ofair
+ CMD workflow-run --uuid ${WORKFLOW_UUID} ---workflow-json ${WORKFLOW_JSON} --parameters ${WORKFLOW_PARAMETERS} --operational-options ${OPERATIONAL_OPTIONS}
```

As a way of testing, where `ls` command would become the real interface:
```console
$ kubectl run --image=busybox batch-857bb969bb-john ls
deployment.apps/batch-857bb969bb-john created
$ kubectl logs batch-857bb969bb-john-64f97d955d-jklcw
bin
dev
etc
home
proc
root
sys
tmp
usr
var
```

It is neccessary to keep reading [the configuration](https://github.com/reanahub/reana-cluster/blob/master/reana_cluster/backends/kubernetes/templates/deployments/serial-default-worker.yaml#L22-L27) we were passing to the static service in the past through REANA-Cluster.
