### ISSUE TITLE
Update job status by message passing using RabbitMQ

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-engine-serial#6]

**Comment by dinosk** [comment]
This can be done with a copy of what is done in: https://github.com/reanahub/reana-workflow-engine-yadage/pull/62/files#diff-deb1d3b5bdfa1fdcd3a9b43c84bf2de6R63

**Comment by dinosk** [comment]
Done in https://github.com/reanahub/reana-workflow-engine-serial/pull/9
